"""
dev.py: start the whole Handshake stack locally, with one command.

    python scripts/dev.py                 backend + mock merchant + frontend
    python scripts/dev.py --no-frontend   backend + mock merchant only

What it does
------------
1. First-run setup, without ever printing a secret:
   - if .env is missing, copy .env.example to .env
   - if no HANDSHAKE_AGENT_TOKEN / signing / session secrets are set, generate
     random ones and APPEND them to .env (never committed; .gitignore covers it)
   - if frontend/.env.local is missing, write it with NEXT_PUBLIC_API_URL and
     NEXT_PUBLIC_USE_MOCKS=false (so the frontend talks to this backend)
2. Starts three processes with prefixed logs: [api] [merchant] [web].
   Ports and URLs come from config.py (HANDSHAKE_API_URL etc.), never literals.
3. Ctrl-C stops all of them cleanly.
"""

from __future__ import annotations

import argparse
import os
import secrets
import shutil
import signal
import subprocess
import sys
import threading
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from handshake import config  # noqa: E402

VENV_BIN = REPO / ".venv" / "bin"
COLORS = {"api": "\033[36m", "merchant": "\033[35m", "web": "\033[32m"}
RESET = "\033[0m"


def ensure_env_file() -> list[str]:
    """Create .env from the example if needed, and append any missing generated secrets. Returns what was generated (names only)."""
    env_path = REPO / ".env"
    example = REPO / ".env.example"
    if not env_path.exists() and example.exists():
        shutil.copyfile(example, env_path)
        os.chmod(env_path, 0o600)

    config.reset_settings()
    settings = config.get_settings()  # loads .env (without printing it)
    additions: dict[str, str] = {}
    if not settings.agent_token:
        additions["HANDSHAKE_AGENT_TOKEN"] = "hs_agent_" + secrets.token_urlsafe(24)
    if settings.signing_secret == config.DEV_SIGNING_SECRET:
        additions["HANDSHAKE_SIGNING_SECRET"] = secrets.token_urlsafe(32)
    if settings.session_secret == config.DEV_SESSION_SECRET:
        additions["HANDSHAKE_SESSION_SECRET"] = secrets.token_urlsafe(32)
    if additions:
        with open(env_path, "a", encoding="utf-8") as handle:
            handle.write("\n# Generated by scripts/dev.py on first run. Never commit this file.\n")
            for name, value in additions.items():
                handle.write(f"{name}={value}\n")
                os.environ[name] = value
        os.chmod(env_path, 0o600)
        config.reset_settings()
    return list(additions)


def ensure_frontend_env() -> bool:
    """Write frontend/.env.local (pointing at this backend, mocks off) if it doesn't exist."""
    path = REPO / "frontend" / ".env.local"
    if path.exists():
        return False
    settings = config.get_settings()
    path.write_text(
        "# Written by scripts/dev.py. Point the frontend at the local backend.\n"
        f"NEXT_PUBLIC_API_URL={settings.api_url}\n"
        "NEXT_PUBLIC_USE_MOCKS=false\n",
        encoding="utf-8",
    )
    return True


def pump(name: str, process: subprocess.Popen) -> None:
    """Copy a child's output to ours, one prefixed line at a time."""
    color = COLORS.get(name, "") if sys.stdout.isatty() else ""
    reset = RESET if color else ""
    for line in iter(process.stdout.readline, ""):
        print(f"{color}[{name}]{reset} {line.rstrip()}", flush=True)


def main() -> int:
    """Set up, start everything, and wait for Ctrl-C."""
    parser = argparse.ArgumentParser(description="Run the Handshake stack locally.")
    parser.add_argument("--no-frontend", action="store_true", help="Skip the Next.js frontend")
    args = parser.parse_args()

    generated = ensure_env_file()
    if generated:
        print(f"[dev] generated into .env (values not shown): {', '.join(generated)}")
    if ensure_frontend_env():
        print("[dev] wrote frontend/.env.local (NEXT_PUBLIC_USE_MOCKS=false)")

    settings = config.get_settings()
    print(f"[dev] {settings.payment_label}; credential mode {settings.credential_mode}; "
          f"compiler {'fixture (offline)' if settings.compiler_uses_fixture else settings.compiler_model}")

    commands: dict[str, tuple[list[str], Path]] = {
        "api": ([str(VENV_BIN / "uvicorn"), "handshake.api:app", "--port", str(settings.api_port)], REPO),
        "merchant": ([str(VENV_BIN / "uvicorn"), "handshake.merchant:app", "--port", str(settings.merchant_port)], REPO),
    }
    if not args.no_frontend:
        npm = shutil.which("npm")
        if npm is None:
            print("[dev] npm not found; starting without the frontend")
        else:
            commands["web"] = ([npm, "run", "dev", "--", "--port", str(settings.frontend_port)], REPO / "frontend")

    processes: dict[str, subprocess.Popen] = {}
    for name, (command, cwd) in commands.items():
        processes[name] = subprocess.Popen(
            command, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1,
            env={**os.environ, "PYTHONUNBUFFERED": "1"}, start_new_session=True,
        )
        threading.Thread(target=pump, args=(name, processes[name]), daemon=True).start()

    print(f"[dev] backend  {settings.api_url}")
    print(f"[dev] merchant {settings.merchant_url}")
    if "web" in processes:
        print(f"[dev] frontend {settings.frontend_url}")
    print("[dev] Ctrl-C to stop")

    def stop(*_: object) -> None:
        """Terminate every child process group, then exit."""
        for process in processes.values():
            if process.poll() is None:
                try:
                    os.killpg(process.pid, signal.SIGTERM)
                except ProcessLookupError:
                    pass
        deadline = time.time() + 8
        for process in processes.values():
            try:
                process.wait(timeout=max(0.1, deadline - time.time()))
            except subprocess.TimeoutExpired:
                os.killpg(process.pid, signal.SIGKILL)
        print("[dev] stopped")
        sys.exit(0)

    signal.signal(signal.SIGINT, stop)
    signal.signal(signal.SIGTERM, stop)
    while True:
        for name, process in processes.items():
            if process.poll() is not None:
                print(f"[dev] {name} exited with code {process.returncode}; stopping everything")
                stop()
        time.sleep(0.5)


if __name__ == "__main__":
    sys.exit(main())
